version: '3'
services:
  libreflow-client:
    build: ./
    container_name: libreflow-client
    command: pnpm run dev --host
    environment:
      PORT: 3000
      NODE_ENV: "development"
    ports:
      - 3000:3000
    volumes:
      - ./:/libreflow-client
    networks:
      - libreflow

  libreflow-server:
    build: ../server
    container_name: libreflow-server
    command: pnpm run dev --host
    links:
      - libreflow-db:libreflow-db
    environment:
      PORT: 3004
      DB_CONNECTION: libreflow-db
      DB_PORT: 5432
      NODE_ENV: "development"
    ports:
      - 3004:3004
    volumes:
      - ../server/:/libreflow-server
    networks:
      - libreflow

  libreflow-db:
    build: ../database
    ports:
      - "5430:5432"
    networks:
      - libreflow

networks:
  libreflow:
    driver: bridge