version: '3'
services:
  #nginx:
  #  build: ./nginx
  #  links:
  #    - app:app
  #  ports:
  #    - "8080:8080"

  #app:
  #  build: ./app
  #  links:
  #    - db
  #  environment:
  #    PORT: 3000
  #    DB_CONNECTION: postgres://user:secure1@db/main
  #    NODE_ENV: "development"
  #  ports:
  #    - "3000:3000"

  db:
    build: ./postgres
    ports:
      - "5430:5432"
