-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.boards
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    workspace_id integer NOT NULL,
    uid character varying(36) COLLATE pg_catalog."default",
    CONSTRAINT boards_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cards
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description text COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    list_id integer NOT NULL,
    additional json[],
    uid character varying(36) COLLATE pg_catalog."default",
    CONSTRAINT cards_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.link_cards_tags
(
    card_id integer NOT NULL,
    tag_id integer NOT NULL,
    CONSTRAINT link_cards_tags_pkey PRIMARY KEY (card_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.lists
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    board_id integer NOT NULL,
    uid character varying(36) COLLATE pg_catalog."default",
    CONSTRAINT lists_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.workspaces
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    uid character varying(36) COLLATE pg_catalog."default",
    CONSTRAINT workspaces_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tags
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    color character varying(6) COLLATE pg_catalog."default",
    board_id integer NOT NULL,
    uid character varying(36) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tags_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.boards
    ADD CONSTRAINT "FK_BOARDS_WORKSPACE_ID" FOREIGN KEY (workspace_id)
    REFERENCES public.workspaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cards
    ADD CONSTRAINT "FK_CARDS_LIST_ID" FOREIGN KEY (list_id)
    REFERENCES public.lists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.link_cards_tags
    ADD CONSTRAINT "FK_LINK_CARD_ID" FOREIGN KEY (card_id)
    REFERENCES public.cards (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.link_cards_tags
    ADD CONSTRAINT "FK_LINK_TAG_ID" FOREIGN KEY (tag_id)
    REFERENCES public.tags (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lists
    ADD CONSTRAINT "FK_LISTS_BOARD_ID" FOREIGN KEY (board_id)
    REFERENCES public.boards (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tags
    ADD CONSTRAINT "FK_TAG_BOARD_ID" FOREIGN KEY (board_id)
    REFERENCES public.boards (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;